import { IOrder } from '../types';

export const sampleSeedOrders: IOrder[] = [
  {
    orderNumber: 'LS-20260920-00084',
    customer: 'cust-101',
    shippingDetails: {
      fullName: 'Ayesha Khan',
      phone: '03001234567',
      whatsapp: '03001234567',
      city: 'Lahore',
      area: 'Gulberg III',
      address: 'House 14-B, Street 3, Main Market Gulberg III',
      landmark: 'Near Siddique Trade Centre',
      notes: 'Please call before delivery',
    },
    items: [
      {
        productId: 'prod-101',
        productName: 'Zartaj Luxury Embroidered 3-Piece Lawn Suit',
        sku: 'LS-101',
        variantSku: 'LS-101-EMR-M',
        color: 'Emerald Green',
        size: 'M',
        unitPrice: 4250,
        quantity: 1,
        subtotal: 4250,
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 4250,
    deliveryCharge: 0,
    totalAmount: 4250,
    paymentMethod: 'COD',
    status: 'Delivered',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 48),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
      {
        status: 'Confirmed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 46),
        note: 'Order confirmed via customer verification call.',
      },
      {
        status: 'Packed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 36),
        note: 'Quality checked and packed in Noor & Co. luxury signature box.',
      },
      {
        status: 'Shipped',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 24),
        note: 'Handed over to TCS Express courier.',
      },
      {
        status: 'Delivered',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
        note: 'Delivered and cash collected (PKR 4,250).',
      },
    ],
    source: 'website',
    trackingCode: 'TCS-98231450',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 48),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
  },
  {
    orderNumber: 'LS-20260921-00088',
    customer: 'cust-102',
    shippingDetails: {
      fullName: 'Fatima Zahra',
      phone: '03219876543',
      whatsapp: '03219876543',
      city: 'Karachi',
      area: 'Clifton Block 4',
      address: 'Apartment 402, Sea Breeze Residency, Clifton Block 4',
      landmark: 'Near Bilawal House',
      notes: 'Ring bell on arrival',
    },
    items: [
      {
        productId: 'prod-102',
        productName: 'Mehr-un-Nisa Chiffon Formal 3-Piece',
        sku: 'LS-102',
        variantSku: 'LS-102-NAVY-L',
        color: 'Royal Navy',
        size: 'L',
        unitPrice: 5850,
        quantity: 1,
        subtotal: 5850,
        image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 5850,
    deliveryCharge: 0,
    totalAmount: 5850,
    paymentMethod: 'COD',
    status: 'Shipped',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
      {
        status: 'Confirmed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 28),
        note: 'Confirmed via WhatsApp.',
      },
      {
        status: 'Shipped',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 14),
        note: 'Dispatched with Leopards Courier. Air cargo tracking active.',
      },
    ],
    source: 'website',
    trackingCode: 'LEO-77123901',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 30),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 14),
  },
  {
    orderNumber: 'LS-20260921-00093',
    customer: 'cust-103',
    shippingDetails: {
      fullName: 'Mahnoor Ali',
      phone: '03335551234',
      whatsapp: '03335551234',
      city: 'Islamabad',
      area: 'Sector F-7/2',
      address: 'House 22, Street 41, Sector F-7/2',
      landmark: 'Near Jinnah Super Market',
      notes: '',
    },
    items: [
      {
        productId: 'prod-103',
        productName: 'Gul-e-Daudi Printed 2-Piece Lawn Pair',
        sku: 'LS-103',
        variantSku: 'LS-103-ROSE-S',
        color: 'Dusty Rose',
        size: 'S',
        unitPrice: 2850,
        quantity: 1,
        subtotal: 2850,
        image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 2850,
    deliveryCharge: 250,
    totalAmount: 3100,
    paymentMethod: 'COD',
    status: 'Packed',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 20),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
      {
        status: 'Confirmed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 18),
        note: 'Order confirmed with customer.',
      },
      {
        status: 'Packed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 6),
        note: 'Packed and awaiting rider courier pickup.',
      },
    ],
    source: 'website',
    trackingCode: 'TCS-98334120',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 20),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 6),
  },
  {
    orderNumber: 'LS-20260922-00097',
    customer: 'cust-104',
    shippingDetails: {
      fullName: 'Zainab Tariq',
      phone: '03451122334',
      whatsapp: '03451122334',
      city: 'Faisalabad',
      area: 'Kohinoor City',
      address: 'House 89, Block C, Kohinoor City',
      landmark: 'Near D-Ground',
      notes: 'Leave at gate if not answering',
    },
    items: [
      {
        productId: 'prod-104',
        productName: 'Shahana Hand-Embroidered Organza Formals',
        sku: 'LS-104',
        variantSku: 'LS-104-PINK-M',
        color: 'Blush Pink',
        size: 'M',
        unitPrice: 6450,
        quantity: 1,
        subtotal: 6450,
        image: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 6450,
    deliveryCharge: 0,
    totalAmount: 6450,
    paymentMethod: 'COD',
    status: 'Processing',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 12),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
      {
        status: 'Confirmed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 10),
        note: 'Confirmed by phone call.',
      },
      {
        status: 'Processing',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4),
        note: 'Fabric being steamed and prepared in dispatch unit.',
      },
    ],
    source: 'website',
    trackingCode: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 12),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 4),
  },
  {
    orderNumber: 'LS-20260922-00100',
    customer: 'cust-105',
    shippingDetails: {
      fullName: 'Hira Bilal',
      phone: '03027788990',
      whatsapp: '03027788990',
      city: 'Multan',
      area: 'Multan Cantt',
      address: 'Bungalow 18, Officers Colony, Cantt',
      landmark: 'Near Army Public School',
      notes: '',
    },
    items: [
      {
        productId: 'prod-105',
        productName: 'Noor-e-Kashmir Velvet Pret 2-Piece',
        sku: 'LS-105',
        variantSku: 'LS-105-PLUM-L',
        color: 'Plum Purple',
        size: 'L',
        unitPrice: 7200,
        quantity: 1,
        subtotal: 7200,
        image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 7200,
    deliveryCharge: 0,
    totalAmount: 7200,
    paymentMethod: 'COD',
    status: 'Confirmed',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 8),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
      {
        status: 'Confirmed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 5),
        note: 'Customer verified address via automated SMS & call.',
      },
    ],
    source: 'website',
    trackingCode: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 8),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 5),
  },
  {
    orderNumber: 'LS-20260922-00102',
    customer: 'cust-106',
    shippingDetails: {
      fullName: 'Sana Malik',
      phone: '03124455667',
      whatsapp: '03124455667',
      city: 'Rawalpindi',
      area: 'Bahria Town Phase 4',
      address: 'House 312, Sector C, Street 15, Bahria Town Phase 4',
      landmark: 'Civic Centre',
      notes: 'Call before arriving',
    },
    items: [
      {
        productId: 'prod-106',
        productName: 'Dariya Digital Printed Cambric 2-Piece',
        sku: 'LS-106',
        variantSku: 'LS-106-TEAL-UNST',
        color: 'Deep Teal',
        size: 'Unstitched',
        unitPrice: 2450,
        quantity: 1,
        subtotal: 2450,
        image: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 2450,
    deliveryCharge: 250,
    totalAmount: 2700,
    paymentMethod: 'COD',
    status: 'Order Placed',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 95),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
    ],
    source: 'website',
    trackingCode: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 95),
    updatedAt: new Date(Date.now() - 1000 * 60 * 95),
  },
  {
    orderNumber: 'LS-20260922-00103',
    customer: 'cust-107',
    shippingDetails: {
      fullName: 'Maryam Siddiqui',
      phone: '03348899001',
      whatsapp: '03348899001',
      city: 'Peshawar',
      area: 'University Town',
      address: 'House 5, Park Road, University Town',
      landmark: 'Near Peshawar Club',
      notes: '',
    },
    items: [
      {
        productId: 'prod-107',
        productName: 'Ruhab Festive Jacquard 3-Piece',
        sku: 'LS-107',
        variantSku: 'LS-107-MAR-M',
        color: 'Deep Maroon',
        size: 'M',
        unitPrice: 5200,
        quantity: 1,
        subtotal: 5200,
        image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 5200,
    deliveryCharge: 0,
    totalAmount: 5200,
    paymentMethod: 'COD',
    status: 'Order Placed',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 35),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
    ],
    source: 'website',
    trackingCode: null,
    createdAt: new Date(Date.now() - 1000 * 60 * 35),
    updatedAt: new Date(Date.now() - 1000 * 60 * 35),
  },
  {
    orderNumber: 'LS-20260920-00081',
    customer: 'cust-108',
    shippingDetails: {
      fullName: 'Usman Ghani',
      phone: '03051239876',
      whatsapp: '03051239876',
      city: 'Sialkot',
      area: 'Paris Road',
      address: 'Plot 44, Commercial Zone, Paris Road',
      landmark: 'Near Chamber of Commerce',
      notes: 'Office hours 9am - 6pm',
    },
    items: [
      {
        productId: 'prod-101',
        productName: 'Zartaj Luxury Embroidered 3-Piece Lawn Suit',
        sku: 'LS-101',
        variantSku: 'LS-101-RUBY-XL',
        color: 'Ruby Red',
        size: 'XL',
        unitPrice: 4250,
        quantity: 1,
        subtotal: 4250,
        image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
      },
    ],
    subtotal: 4250,
    deliveryCharge: 0,
    totalAmount: 4250,
    paymentMethod: 'COD',
    status: 'Delivered',
    statusHistory: [
      {
        status: 'Order Placed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 55),
        note: 'Customer placed Cash on Delivery order via website storefront.',
      },
      {
        status: 'Confirmed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 50),
        note: 'Confirmed with customer.',
      },
      {
        status: 'Packed',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 42),
        note: 'Packed and dispatched.',
      },
      {
        status: 'Shipped',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 30),
        note: 'With TCS Courier.',
      },
      {
        status: 'Delivered',
        timestamp: new Date(Date.now() - 1000 * 60 * 60 * 15),
        note: 'Payment collected by rider.',
      },
    ],
    source: 'website',
    trackingCode: 'TCS-98112009',
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 55),
    updatedAt: new Date(Date.now() - 1000 * 60 * 60 * 15),
  },
];
