import { ICategory, IProduct } from '../types';

export const demoCategories: ICategory[] = [
  {
    name: '3 Piece Suits',
    slug: '3-piece-suits',
    description: 'Complete 3-piece luxury unstitched & ready-to-wear lawn, chiffon, and embroidered collections.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=600&q=80',
    displayOrder: 1,
    isActive: true,
  },
  {
    name: '2 Piece Suits',
    slug: '2-piece-suits',
    description: 'Everyday chic and printed shirt-trouser and shirt-dupatta pairs.',
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=600&q=80',
    displayOrder: 2,
    isActive: true,
  },
  {
    name: 'Unstitched',
    slug: 'unstitched',
    description: 'Premium unstitched fabrics ready for bespoke tailoring.',
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=600&q=80',
    displayOrder: 3,
    isActive: true,
  },
  {
    name: 'Ready to Wear',
    slug: 'ready-to-wear',
    description: 'Pre-stitched pret kurtis, matching co-ords, and festive ensembles.',
    image: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=600&q=80',
    displayOrder: 4,
    isActive: true,
  },
  {
    name: 'Luxury Lawn',
    slug: 'luxury-lawn',
    description: 'Breathable summer lawn with intricate neckline embroidery and silk/chiffon dupattas.',
    image: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=600&q=80',
    displayOrder: 5,
    isActive: true,
  },
  {
    name: 'Festive & Chiffon',
    slug: 'festive-chiffon',
    description: 'Heavily embellished formals and festive wedding guest attire.',
    image: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=600&q=80',
    displayOrder: 6,
    isActive: true,
  },
  {
    name: 'Cambric & Cotton',
    slug: 'cotton',
    description: 'Soft 100% pure cotton and daily wear breathable cambric fabrics.',
    image: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=600&q=80',
    displayOrder: 7,
    isActive: true,
  },
  {
    name: 'New Arrivals',
    slug: 'new-arrivals',
    description: 'Fresh from the loom - the newest seasonal catalogue releases.',
    image: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=600&q=80',
    displayOrder: 8,
    isActive: true,
  },
  {
    name: 'Best Sellers',
    slug: 'best-sellers',
    description: 'Most-loved classic designs customer-rated across Pakistan.',
    image: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=600&q=80',
    displayOrder: 9,
    isActive: true,
  },
  {
    name: 'Sale',
    slug: 'sale',
    description: 'Limited-time discounts on iconic seasonal suites.',
    image: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=600&q=80',
    displayOrder: 10,
    isActive: true,
  }
];

export const demoProducts: IProduct[] = [
  {
    id: 'prod-101',
    name: 'Zartaj Luxury Embroidered 3-Piece Lawn Suit',
    slug: 'zartaj-luxury-embroidered-3-piece-lawn-suit',
    sku: 'LS-101',
    description: 'Exquisite 3-piece luxury lawn ensemble featuring intricate multi-thread floral embroidery on the front neckline, paired with a digital printed lightweight silk dupatta and dyed cambric trouser.',
    category: '3-piece-suits',
    tags: ['luxury lawn', '3 piece', 'embroidered', 'summer', 'festive'],
    basePrice: 4250,
    compareAtPrice: 4950,
    fabric: 'Luxury Swiss Lawn',
    shirtDetails: 'Embroidered Swiss lawn front (1.25m), digital printed lawn back & sleeves (1.75m), embroidered organza daman border.',
    trouserDetails: 'Dyed premium solid cambric trouser with embroidered lace patch (2.5m).',
    dupattaDetails: 'Digital printed pure medium silk dupatta with four-sided finishing (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43" | XL: 46"',
      length: '40" (Standard Kurti Length)',
      sleeve: '21" Full Sleeves with Cuff Border',
      trouser: '38" Straight Cut Pants',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        alt: 'Zartaj Luxury Embroidered Lawn Suit in Emerald Green',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
        alt: 'Neckline embroidery detail',
        isPrimary: false,
      },
      {
        url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
        alt: 'Silk dupatta draping view',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-101-EMR-S', color: 'Emerald Green', colorCode: '#134E3F', size: 'S', stock: 6 },
      { sku: 'LS-101-EMR-M', color: 'Emerald Green', colorCode: '#134E3F', size: 'M', stock: 8 },
      { sku: 'LS-101-EMR-L', color: 'Emerald Green', colorCode: '#134E3F', size: 'L', stock: 4 },
      { sku: 'LS-101-EMR-UN', color: 'Emerald Green', colorCode: '#134E3F', size: 'Unstitched', stock: 12 },
      { sku: 'LS-101-PLM-M', color: 'Deep Plum', colorCode: '#4A154B', size: 'M', stock: 5 },
      { sku: 'LS-101-PLM-L', color: 'Deep Plum', colorCode: '#4A154B', size: 'L', stock: 3 },
    ],
    status: 'active',
    featured: true,
    newArrival: true,
    bestSeller: true,
    sale: true,
  },
  {
    id: 'prod-102',
    name: 'Gul-e-Rana Block Print 2-Piece Lawn Suit',
    slug: 'gul-e-rana-block-print-2-piece-lawn-suit',
    sku: 'LS-102',
    description: 'Vibrant handcrafted Mughal block print shirt with matching coordinated straight trousers. Breathable 100% fine cotton lawn for daily comfort and effortless elegance.',
    category: '2-piece-suits',
    tags: ['2 piece', 'block print', 'cotton', 'daily wear', 'lawn'],
    basePrice: 2450,
    compareAtPrice: null,
    fabric: 'Fine Combed Lawn',
    shirtDetails: 'Hand block-printed lawn shirt front, back, and sleeves (3.0m total).',
    trouserDetails: 'Matching dyed block-printed cambric straight trouser (2.5m).',
    dupattaDetails: 'Not included (2-piece shirt & trouser pair).',
    measurements: {
      chest: 'Small: 37" | Medium: 40" | Large: 42"',
      length: '38" Flared A-Line Cut',
      sleeve: '20" Quarter-Length Folded Cuffs',
      trouser: '38" Elasticated Waistband',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        alt: 'Gul-e-Rana Block Print Kurti & Trouser in Terracotta',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=800&q=80',
        alt: 'Fabric texture and sleeve print',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-102-TER-S', color: 'Terracotta Rust', colorCode: '#C85A32', size: 'S', stock: 5 },
      { sku: 'LS-102-TER-M', color: 'Terracotta Rust', colorCode: '#C85A32', size: 'M', stock: 10 },
      { sku: 'LS-102-TER-L', color: 'Terracotta Rust', colorCode: '#C85A32', size: 'L', stock: 3 },
      { sku: 'LS-102-IND-S', color: 'Indigo Blue', colorCode: '#1A365D', size: 'S', stock: 4 },
      { sku: 'LS-102-IND-M', color: 'Indigo Blue', colorCode: '#1A365D', size: 'M', stock: 6 },
    ],
    status: 'active',
    featured: true,
    newArrival: true,
    bestSeller: false,
    sale: false,
  },
  {
    id: 'prod-103',
    name: 'Noor-e-Jahan Chiffon Festive 3-Piece Formal',
    slug: 'noor-e-jahan-chiffon-festive-3-piece-formal',
    sku: 'LS-103',
    description: 'Regal bridal wedding guest attire woven from pure crinkle chiffon with zari, tilla, and sequins embroidery across front panels and hem. Complete with heavy embroidered net dupatta and raw silk trouser.',
    category: 'festive-chiffon',
    tags: ['chiffon', 'festive', 'wedding wear', 'embroidered', 'luxury'],
    basePrice: 8450,
    compareAtPrice: 9950,
    fabric: 'Pure Crinkle Chiffon & Raw Silk',
    shirtDetails: 'Heavy tilla & sequin embroidered chiffon front & back with hand-embellished neckline (3.25m).',
    trouserDetails: 'Dyed Korean raw silk straight pants (2.5m).',
    dupattaDetails: 'Delicate embroidered net dupatta with scalloped borders (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 41" | Large: 44"',
      length: '46" Long Formal Frock/Maxi Cut',
      sleeve: '22" Sheer Embroidered Chiffon Sleeves',
      trouser: '39" Tailored Trousers',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=800&q=80',
        alt: 'Noor-e-Jahan Royal Gold & Ivory Festive Formal',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        alt: 'Tilla embroidery and sequin work details',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-103-GLD-S', color: 'Champagne Gold', colorCode: '#D4AF37', size: 'S', stock: 2 },
      { sku: 'LS-103-GLD-M', color: 'Champagne Gold', colorCode: '#D4AF37', size: 'M', stock: 4 },
      { sku: 'LS-103-GLD-L', color: 'Champagne Gold', colorCode: '#D4AF37', size: 'L', stock: 2 },
      { sku: 'LS-103-GLD-UN', color: 'Champagne Gold', colorCode: '#D4AF37', size: 'Unstitched', stock: 6 },
    ],
    status: 'active',
    featured: true,
    newArrival: false,
    bestSeller: true,
    sale: true,
  },
  {
    id: 'prod-104',
    name: 'Aafreen Printed Lawn 3-Piece with Voile Dupatta',
    slug: 'aafreen-printed-lawn-3-piece-with-voile-dupatta',
    sku: 'LS-104',
    description: 'Refreshing pastel geometric and ethnic print 3-piece suit made from ultra-soft summer lawn, paired with an airy feather-light voile dupatta for summer breeze comfort.',
    category: '3-piece-suits',
    tags: ['printed', 'lawn', '3 piece', 'summer lawn', 'daily wear'],
    basePrice: 2850,
    compareAtPrice: 3200,
    fabric: 'Fine Pakistani Lawn',
    shirtDetails: 'Digital printed lawn shirt (3.0m).',
    trouserDetails: 'Dyed breathable cotton trouser (2.5m).',
    dupattaDetails: 'Matching digital printed soft lawn voile dupatta (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43"',
      length: '39" Traditional Straight Kurti',
      sleeve: '21" Sleeves',
      trouser: '38" Relaxed Shalwar/Trouser Cut',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
        alt: 'Aafreen Pastel Floral Summer Lawn 3-Piece',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
        alt: 'Voile dupatta and print clarity',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-104-PCH-S', color: 'Blush Peach', colorCode: '#FFDAB9', size: 'S', stock: 8 },
      { sku: 'LS-104-PCH-M', color: 'Blush Peach', colorCode: '#FFDAB9', size: 'M', stock: 12 },
      { sku: 'LS-104-PCH-L', color: 'Blush Peach', colorCode: '#FFDAB9', size: 'L', stock: 6 },
      { sku: 'LS-104-PCH-UN', color: 'Blush Peach', colorCode: '#FFDAB9', size: 'Unstitched', stock: 15 },
      { sku: 'LS-104-MNT-M', color: 'Mint Green', colorCode: '#98FF98', size: 'M', stock: 7 },
      { sku: 'LS-104-MNT-L', color: 'Mint Green', colorCode: '#98FF98', size: 'L', stock: 4 },
    ],
    status: 'active',
    featured: false,
    newArrival: true,
    bestSeller: true,
    sale: true,
  },
  {
    id: 'prod-105',
    name: 'Sitara Ready-to-Wear Embroidered Pret Kurti',
    slug: 'sitara-ready-to-wear-embroidered-pret-kurti',
    sku: 'LS-105',
    description: 'Instant sophistication in pure jacquard cotton. Features delicate Kashmiri thread embroidery on the collar, stylish tassel buttons on the placket, and bell sleeves with lace inserts.',
    category: 'ready-to-wear',
    tags: ['ready to wear', 'pret', 'kurti', 'embroidered', 'cotton'],
    basePrice: 1950,
    compareAtPrice: null,
    fabric: 'Textured Jacquard Cotton',
    shirtDetails: 'Single stitched pret kurti with organza sleeve details and wooden button loops.',
    trouserDetails: 'Single top only (Trouser sold separately).',
    dupattaDetails: 'Not included.',
    measurements: {
      chest: 'XS: 36" | Small: 38" | Medium: 40" | Large: 43" | XL: 46"',
      length: '37" Hip-length Box Cut Kurti',
      sleeve: '20" Flared Bell Sleeves',
      trouser: 'N/A',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
        alt: 'Sitara Pret Kurti in Ivory White',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=800&q=80',
        alt: 'Embroidered collar and front button placket',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-105-IVR-XS', color: 'Ivory White', colorCode: '#FFFFF0', size: 'XS', stock: 3 },
      { sku: 'LS-105-IVR-S', color: 'Ivory White', colorCode: '#FFFFF0', size: 'S', stock: 6 },
      { sku: 'LS-105-IVR-M', color: 'Ivory White', colorCode: '#FFFFF0', size: 'M', stock: 9 },
      { sku: 'LS-105-IVR-L', color: 'Ivory White', colorCode: '#FFFFF0', size: 'L', stock: 5 },
      { sku: 'LS-105-IVR-XL', color: 'Ivory White', colorCode: '#FFFFF0', size: 'XL', stock: 2 },
    ],
    status: 'active',
    featured: false,
    newArrival: false,
    bestSeller: true,
    sale: false,
  },
  {
    id: 'prod-106',
    name: 'Bahar-e-Nau Unstitched 3-Piece Embroidered Lawn',
    slug: 'bahar-e-nau-unstitched-3-piece-embroidered-lawn',
    sku: 'LS-106',
    description: 'An ode to spring blossoms. Heavy schiffli chikankari embroidered front with organza embroidered daman border, paired with jacquard lawn dupatta and soft cambric trouser.',
    category: 'unstitched',
    tags: ['unstitched', 'chikankari', 'lawn', '3 piece', 'embroidered'],
    basePrice: 5200,
    compareAtPrice: 5800,
    fabric: 'Schiffli Embroidered Lawn',
    shirtDetails: 'Schiffli chikankari lawn front (1.25m), printed lawn back & sleeves (1.75m), 2 organza embroidered borders.',
    trouserDetails: 'Dyed premium cambric trouser (2.5m).',
    dupattaDetails: 'Subtle woven jacquard lawn dupatta with fringed pallu (2.5m).',
    measurements: {
      chest: 'Unstitched - Custom Tailoring Fabric Included',
      length: 'Fabric accommodates up to 48" shirt length',
      sleeve: 'Up to 24" sleeves with borders',
      trouser: '2.5 Meter Trouser Fabric',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        alt: 'Bahar-e-Nau Schiffli Lawn in Mustard Yellow',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
        alt: 'Schiffli embroidery work closeup',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-106-YEL-UN', color: 'Mustard Gold', colorCode: '#E1AD01', size: 'Unstitched', stock: 14 },
      { sku: 'LS-106-CYN-UN', color: 'Powder Cyan', colorCode: '#4682B4', size: 'Unstitched', stock: 8 },
    ],
    status: 'active',
    featured: true,
    newArrival: true,
    bestSeller: false,
    sale: true,
  },
  {
    id: 'prod-107',
    name: 'Kashish Pure Cotton 2-Piece Solid Co-ord Set',
    slug: 'kashish-pure-cotton-2-piece-solid-co-ord-set',
    sku: 'LS-107',
    description: 'Modern minimalist monochromatic matching co-ord set in breathable Egyptian cotton. Clean tailoring with drop-shoulder silhouette, curved hemline, and wide-leg culotte trousers.',
    category: '2-piece-suits',
    tags: ['co-ord', 'solid', 'cotton', '2 piece', 'ready to wear', 'minimalist'],
    basePrice: 3150,
    compareAtPrice: null,
    fabric: '100% Egyptian Combed Cotton',
    shirtDetails: 'Stitched button-down tunic shirt with mandarin band collar.',
    trouserDetails: 'Stitched matching wide-leg cropped trousers with side pockets.',
    dupattaDetails: 'Co-ord ensemble (no dupatta).',
    measurements: {
      chest: 'Small: 39" | Medium: 42" | Large: 45" (Relaxed Drop Shoulder Fit)',
      length: '36" Tunic Length',
      sleeve: '19" Fold-up Cuffs',
      trouser: '37" Wide-Leg Culottes',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
        alt: 'Kashish Solid Co-ord Set in Forest Sage',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        alt: 'Fabric weave and matching pants',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-107-SGE-S', color: 'Sage Green', colorCode: '#9CAF88', size: 'S', stock: 4 },
      { sku: 'LS-107-SGE-M', color: 'Sage Green', colorCode: '#9CAF88', size: 'M', stock: 7 },
      { sku: 'LS-107-SGE-L', color: 'Sage Green', colorCode: '#9CAF88', size: 'L', stock: 5 },
      { sku: 'LS-107-BLK-S', color: 'Charcoal Black', colorCode: '#1A1A1A', size: 'S', stock: 5 },
      { sku: 'LS-107-BLK-M', color: 'Charcoal Black', colorCode: '#1A1A1A', size: 'M', stock: 8 },
      { sku: 'LS-107-BLK-L', color: 'Charcoal Black', colorCode: '#1A1A1A', size: 'L', stock: 4 },
    ],
    status: 'active',
    featured: false,
    newArrival: true,
    bestSeller: true,
    sale: false,
  },
  {
    id: 'prod-108',
    name: 'Mehndi & Mayun Festive Embroidered Kurta Trouser',
    slug: 'mehndi-mayun-festive-embroidered-kurta-trouser',
    sku: 'LS-108',
    description: 'Festive occasion wear featuring hand mirror-work and gota patti borders on a cheerful turmeric yellow lawn silk canvas. Includes raw silk capri trousers.',
    category: 'festive-chiffon',
    tags: ['mehndi', 'festive', 'gota work', '2 piece', 'embroidered'],
    basePrice: 4850,
    compareAtPrice: 5500,
    fabric: 'Lawn Silk & Korean Raw Silk',
    shirtDetails: 'Hand mirror-embellished lawn silk kurta with gota border accents.',
    trouserDetails: 'Matching dyed raw silk capri trouser with mirror-work cuff hem.',
    dupattaDetails: 'Optional dupatta available under separate listing.',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43"',
      length: '42" Long Festive Stitched Kurta',
      sleeve: '21" Sleeves with Gota Trims',
      trouser: '38" Fitted Capri Pants',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=800&q=80',
        alt: 'Turmeric Yellow Mehndi Festive Suit',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=800&q=80',
        alt: 'Gota patti and mirror details',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-108-YLW-S', color: 'Turmeric Yellow', colorCode: '#FFC000', size: 'S', stock: 3 },
      { sku: 'LS-108-YLW-M', color: 'Turmeric Yellow', colorCode: '#FFC000', size: 'M', stock: 5 },
      { sku: 'LS-108-YLW-L', color: 'Turmeric Yellow', colorCode: '#FFC000', size: 'L', stock: 3 },
    ],
    status: 'active',
    featured: true,
    newArrival: false,
    bestSeller: false,
    sale: true,
  },
  {
    id: 'prod-109',
    name: 'Sadaf Classic White-on-White Chickenkari 3-Piece',
    slug: 'sadaf-classic-white-on-white-chickenkari-3-piece',
    sku: 'LS-109',
    description: 'Timeless heirloom white chickenkari embroidery on pure pima cotton lawn. Paired with an all-over embroidered shadow-work dupatta and chickenkari bordered trousers.',
    category: 'luxury-lawn',
    tags: ['white on white', 'chickenkari', 'luxury lawn', 'classic', '3 piece'],
    basePrice: 6200,
    compareAtPrice: 6900,
    fabric: 'Pure Pima Cotton Lawn',
    shirtDetails: 'Heavy tonal white chickenkari embroidered front and daman border (3.0m).',
    trouserDetails: 'Pure cotton trouser with chickenkari bottom lace patch (2.5m).',
    dupattaDetails: 'Organza chickenkari embroidered dupatta with pearl scalloped lace (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 41" | Large: 44" | XL: 47"',
      length: '41" Elegant Straight Cut',
      sleeve: '21" Sleeves with Lace',
      trouser: '39" Tailored Trousers',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
        alt: 'Sadaf Pure White Chickenkari Ensemble',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        alt: 'Close up of white shadow embroidery',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-109-WHT-S', color: 'Pristine White', colorCode: '#FDFBF7', size: 'S', stock: 4 },
      { sku: 'LS-109-WHT-M', color: 'Pristine White', colorCode: '#FDFBF7', size: 'M', stock: 6 },
      { sku: 'LS-109-WHT-L', color: 'Pristine White', colorCode: '#FDFBF7', size: 'L', stock: 4 },
      { sku: 'LS-109-WHT-UN', color: 'Pristine White', colorCode: '#FDFBF7', size: 'Unstitched', stock: 10 },
    ],
    status: 'active',
    featured: true,
    newArrival: false,
    bestSeller: true,
    sale: true,
  },
  {
    id: 'prod-110',
    name: 'Dilkash Everyday Printed Lawn Shirt & Dupatta',
    slug: 'dilkash-everyday-printed-lawn-shirt-dupatta',
    sku: 'LS-110',
    description: 'Effortless 2-piece pairing containing digital printed floral shirt and coordinating printed chiffon dupatta. Perfect for university, office, and casual daytime errands.',
    category: '2-piece-suits',
    tags: ['2 piece', 'shirt dupatta', 'printed', 'casual', 'lawn'],
    basePrice: 2150,
    compareAtPrice: null,
    fabric: 'Fine Lawn & Chiffon Dupatta',
    shirtDetails: 'Digital printed lawn shirt (2.75m).',
    trouserDetails: 'Not included (Shirt & Dupatta 2-Piece).',
    dupattaDetails: 'Soft digital printed crinkle chiffon dupatta (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43"',
      length: '39" Traditional Cut',
      sleeve: '20.5" Straight Sleeves',
      trouser: 'N/A',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
        alt: 'Dilkash Printed Shirt and Dupatta in Rose Pink',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        alt: 'Chiffon dupatta drape details',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-110-ROSE-S', color: 'Rose Dust', colorCode: '#C08081', size: 'S', stock: 6 },
      { sku: 'LS-110-ROSE-M', color: 'Rose Dust', colorCode: '#C08081', size: 'M', stock: 9 },
      { sku: 'LS-110-ROSE-L', color: 'Rose Dust', colorCode: '#C08081', size: 'L', stock: 4 },
      { sku: 'LS-110-ROSE-UN', color: 'Rose Dust', colorCode: '#C08081', size: 'Unstitched', stock: 12 },
    ],
    status: 'active',
    featured: false,
    newArrival: true,
    bestSeller: false,
    sale: false,
  },
  {
    id: 'prod-111',
    name: 'Shehnai Organza Embroidered 3-Piece Formal',
    slug: 'shehnai-organza-embroidered-3-piece-formal',
    sku: 'LS-111',
    description: 'Festive masterpiece crafted from shimmering pure organza fabric. Features heavy resham and badla embroidery on the front, paired with dyed raw silk trousers and an embellished organza dupatta.',
    category: 'festive-chiffon',
    tags: ['organza', 'festive', 'formal', 'wedding', 'embroidered'],
    basePrice: 7950,
    compareAtPrice: 8950,
    fabric: 'Pure Shimmer Organza & Silk',
    shirtDetails: 'Resham and badla hand-embellished organza front with inner slip fabric provided (3.25m).',
    trouserDetails: 'Dyed raw silk straight trouser (2.5m).',
    dupattaDetails: 'Organza dupatta with heavy 4-side embroidered pallu (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 41" | Large: 44"',
      length: '44" Angrakha/A-Line Cut',
      sleeve: '21.5" Sheer Organza Sleeves with Embroidered Cuffs',
      trouser: '39" Tailored Pants',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
        alt: 'Shehnai Organza Formal in Ruby Crimson',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=800&q=80',
        alt: 'Organza embroidery close up',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-111-RBY-S', color: 'Ruby Crimson', colorCode: '#9B111E', size: 'S', stock: 2 },
      { sku: 'LS-111-RBY-M', color: 'Ruby Crimson', colorCode: '#9B111E', size: 'M', stock: 5 },
      { sku: 'LS-111-RBY-L', color: 'Ruby Crimson', colorCode: '#9B111E', size: 'L', stock: 3 },
      { sku: 'LS-111-RBY-UN', color: 'Ruby Crimson', colorCode: '#9B111E', size: 'Unstitched', stock: 6 },
    ],
    status: 'active',
    featured: true,
    newArrival: false,
    bestSeller: false,
    sale: true,
  },
  {
    id: 'prod-112',
    name: 'Rang-e-Hoor Floral Digital Printed 3-Piece Lawn',
    slug: 'rang-e-hoor-floral-digital-printed-3-piece-lawn',
    sku: 'LS-112',
    description: 'High-definition digital floral prints infused with traditional Paisley motifs. Super-fine 80s lawn shirt and lawn dupatta paired with solid dyed trouser.',
    category: '3-piece-suits',
    tags: ['lawn', '3 piece', 'digital print', 'summer', 'floral'],
    basePrice: 2950,
    compareAtPrice: 3450,
    fabric: 'Super Fine 80s Lawn',
    shirtDetails: 'Digital printed 80s lawn shirt front, back, and sleeves (3.0m).',
    trouserDetails: 'Dyed cambric trouser (2.5m).',
    dupattaDetails: 'Digital printed lightweight lawn dupatta (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43"',
      length: '39" Traditional Straight Kurti',
      sleeve: '21" Sleeves with Contrast Border',
      trouser: '38" Straight Cut Trousers',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        alt: 'Rang-e-Hoor Floral 3-Piece Lawn Suit',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
        alt: 'Print pattern details',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-112-LAV-S', color: 'Soft Lavender', colorCode: '#E6E6FA', size: 'S', stock: 5 },
      { sku: 'LS-112-LAV-M', color: 'Soft Lavender', colorCode: '#E6E6FA', size: 'M', stock: 8 },
      { sku: 'LS-112-LAV-L', color: 'Soft Lavender', colorCode: '#E6E6FA', size: 'L', stock: 4 },
      { sku: 'LS-112-LAV-UN', color: 'Soft Lavender', colorCode: '#E6E6FA', size: 'Unstitched', stock: 11 },
    ],
    status: 'active',
    featured: false,
    newArrival: true,
    bestSeller: false,
    sale: true,
  },
  {
    id: 'prod-113',
    name: 'Khaddar Heritage Woven 3-Piece Winter Suit',
    slug: 'khaddar-heritage-woven-3-piece-winter-suit',
    sku: 'LS-113',
    description: 'Traditional Kamalia textured khaddar weave designed for transitional weather. Features rich woolen shawl dupatta with woven jacquard borders and dyed khaddar trousers.',
    category: '3-piece-suits',
    tags: ['khaddar', '3 piece', 'winter collection', 'woven', 'shawl'],
    basePrice: 3850,
    compareAtPrice: 4200,
    fabric: 'Heritage Kamalia Khaddar',
    shirtDetails: 'Dyed textured khaddar with embroidered neckline patch (3.0m).',
    trouserDetails: 'Dyed matching khaddar trouser (2.5m).',
    dupattaDetails: 'Warm jacquard woven wool blend shawl (2.5m).',
    measurements: {
      chest: 'Small: 39" | Medium: 42" | Large: 45"',
      length: '41" Straight Winter Cut',
      sleeve: '21" Sleeves',
      trouser: '39" Warm Khaddar Shalwar/Pants',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        alt: 'Khaddar 3-Piece with Woolen Shawl in Rust Brown',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1490481651871-ab68de25d43d?auto=format&fit=crop&w=800&q=80',
        alt: 'Shawl border and fabric texture',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-113-RST-S', color: 'Rust Brown', colorCode: '#8B3103', size: 'S', stock: 3 },
      { sku: 'LS-113-RST-M', color: 'Rust Brown', colorCode: '#8B3103', size: 'M', stock: 6 },
      { sku: 'LS-113-RST-L', color: 'Rust Brown', colorCode: '#8B3103', size: 'L', stock: 4 },
      { sku: 'LS-113-RST-UN', color: 'Rust Brown', colorCode: '#8B3103', size: 'Unstitched', stock: 9 },
    ],
    status: 'active',
    featured: false,
    newArrival: false,
    bestSeller: true,
    sale: true,
  },
  {
    id: 'prod-114',
    name: 'Afshan Embroidered Mirror-Work Velvet Kurti',
    slug: 'afshan-embroidered-mirror-work-velvet-kurti',
    sku: 'LS-114',
    description: 'Micro 9000 pure Korean velvet pret kurti with intricate real mirror-work and gold zardozi stitching on collar and cuffs. Ideal for winter evening soirées.',
    category: 'ready-to-wear',
    tags: ['velvet', 'ready to wear', 'pret', 'winter', 'mirror work'],
    basePrice: 5450,
    compareAtPrice: 6200,
    fabric: 'Micro 9000 Silk Velvet',
    shirtDetails: 'Single stitched royal velvet kurti with side slits and metal coin embellishments.',
    trouserDetails: 'Single kurti only (Pair with matching silk trousers).',
    dupattaDetails: 'Not included.',
    measurements: {
      chest: 'Small: 38" | Medium: 41" | Large: 44"',
      length: '40" Straight Kurti',
      sleeve: '21" Sleeves with Zardozi Work',
      trouser: 'N/A',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=800&q=80',
        alt: 'Afshan Velvet Kurti in Midnight Teal',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
        alt: 'Velvet texture and mirror embroidery',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-114-TEL-S', color: 'Midnight Teal', colorCode: '#004C54', size: 'S', stock: 2 },
      { sku: 'LS-114-TEL-M', color: 'Midnight Teal', colorCode: '#004C54', size: 'M', stock: 4 },
      { sku: 'LS-114-TEL-L', color: 'Midnight Teal', colorCode: '#004C54', size: 'L', stock: 2 },
    ],
    status: 'active',
    featured: true,
    newArrival: false,
    bestSeller: false,
    sale: true,
  },
  {
    id: 'prod-115',
    name: 'Chashman Swiss Lawn Embroidered 3-Piece Suit',
    slug: 'chashman-swiss-lawn-embroidered-3-piece-suit',
    sku: 'LS-115',
    description: 'Bespoke Swiss lawn in a graceful seafoam green hue. Heavily embroidered front yoke with laser-cut organza motifs, coupled with an embroidered net dupatta and cambric trousers.',
    category: 'luxury-lawn',
    tags: ['swiss lawn', 'luxury lawn', '3 piece', 'laser cut', 'embroidered'],
    basePrice: 5850,
    compareAtPrice: 6500,
    fabric: 'Imported Swiss Voile Lawn',
    shirtDetails: 'Laser-cut and embroidered Swiss lawn front with organza daman lace (3.0m).',
    trouserDetails: 'Dyed cambric trouser with embroidered cuff motifs (2.5m).',
    dupattaDetails: 'Embroidered butterfly net dupatta with scalloped borders (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43"',
      length: '41" Flared Cut',
      sleeve: '21" Sleeves with Organza Inserts',
      trouser: '38" Straight Trousers',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
        alt: 'Chashman Swiss Lawn in Seafoam Green',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        alt: 'Laser-cut neckline details',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-115-SFM-S', color: 'Seafoam Green', colorCode: '#9FE2BF', size: 'S', stock: 4 },
      { sku: 'LS-115-SFM-M', color: 'Seafoam Green', colorCode: '#9FE2BF', size: 'M', stock: 6 },
      { sku: 'LS-115-SFM-L', color: 'Seafoam Green', colorCode: '#9FE2BF', size: 'L', stock: 3 },
      { sku: 'LS-115-SFM-UN', color: 'Seafoam Green', colorCode: '#9FE2BF', size: 'Unstitched', stock: 8 },
    ],
    status: 'active',
    featured: true,
    newArrival: true,
    bestSeller: false,
    sale: true,
  },
  {
    id: 'prod-116',
    name: 'Suhani Monochrome Black & White 2-Piece Kurti Pants',
    slug: 'suhani-monochrome-black-and-white-2-piece-kurti-pants',
    sku: 'LS-116',
    description: 'Iconic monochrome geometric printed lawn kurti with contrast black stitch accents, complemented by tailored off-white cigarette pants.',
    category: '2-piece-suits',
    tags: ['monochrome', 'black and white', '2 piece', 'ready to wear', 'pret'],
    basePrice: 2650,
    compareAtPrice: null,
    fabric: 'Fine Cotton Cambric',
    shirtDetails: 'Stitched printed kurti with contrast piping and black pearl buttons.',
    trouserDetails: 'Stitched off-white tailored cigarette pants with ankle slits.',
    dupattaDetails: 'Not included.',
    measurements: {
      chest: 'Small: 37" | Medium: 40" | Large: 43"',
      length: '38" Straight Kurti',
      sleeve: '20" Sleeves',
      trouser: '38" Cigarette Pants',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1596783074918-c84cb06531ca?auto=format&fit=crop&w=800&q=80',
        alt: 'Suhani Monochrome 2-Piece Ensemble',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
        alt: 'Monochrome print and cuff finishing',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-116-BNW-S', color: 'Black & White', colorCode: '#000000', size: 'S', stock: 6 },
      { sku: 'LS-116-BNW-M', color: 'Black & White', colorCode: '#000000', size: 'M', stock: 9 },
      { sku: 'LS-116-BNW-L', color: 'Black & White', colorCode: '#000000', size: 'L', stock: 4 },
      { sku: 'LS-116-BNW-XL', color: 'Black & White', colorCode: '#000000', size: 'XL', stock: 2 },
    ],
    status: 'active',
    featured: false,
    newArrival: false,
    bestSeller: true,
    sale: false,
  },
  {
    id: 'prod-117',
    name: 'Zeb-un-Nisa Unstitched Jacquard 3-Piece Silk Suit',
    slug: 'zeb-un-nisa-unstitched-jacquard-3-piece-silk-suit',
    sku: 'LS-117',
    description: 'Gold-threaded jacquard self-weave shirt with rich organza embroidered border, finished with a heavy banarsi silk jacquard dupatta and dyed cambric trousers.',
    category: 'unstitched',
    tags: ['jacquard', 'unstitched', 'banarsi', 'festive', '3 piece'],
    basePrice: 6750,
    compareAtPrice: 7500,
    fabric: 'Gold Jacquard Lawn & Banarsi Silk',
    shirtDetails: 'Zari woven jacquard lawn shirt fabric with embroidered neckline strip (3.0m).',
    trouserDetails: 'Dyed cambric trouser (2.5m).',
    dupattaDetails: 'Rich Banarsi woven silk dupatta with gold pallu tassels (2.5m).',
    measurements: {
      chest: 'Unstitched - Custom Tailoring Fabric Included',
      length: 'Fabric accommodates up to 47" shirt length',
      sleeve: 'Up to 23" full sleeves',
      trouser: '2.5 Meter Trouser Fabric',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
        alt: 'Zeb-un-Nisa Jacquard Ensemble in Royal Maroon',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
        alt: 'Banarsi silk dupatta texture',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-117-MRN-UN', color: 'Royal Maroon', colorCode: '#800000', size: 'Unstitched', stock: 7 },
      { sku: 'LS-117-NVY-UN', color: 'Navy Gold', colorCode: '#000080', size: 'Unstitched', stock: 5 },
    ],
    status: 'active',
    featured: true,
    newArrival: false,
    bestSeller: false,
    sale: true,
  },
  {
    id: 'prod-118',
    name: 'Meena Bazaar Block-Printed Daily Lawn Kurti',
    slug: 'meena-bazaar-block-printed-daily-lawn-kurti',
    sku: 'LS-118',
    description: 'Charming Indigo and turmeric Ajrak-inspired block print kurti with comfortable loose fit and wooden potli buttons. Crafted for everyday Pakistani summer wear.',
    category: 'ready-to-wear',
    tags: ['kurti', 'ajrak', 'block print', 'daily wear', 'lawn'],
    basePrice: 1750,
    compareAtPrice: null,
    fabric: 'Pure Cotton Lawn',
    shirtDetails: 'Single stitched kurti with wooden potli buttons.',
    trouserDetails: 'Single top only.',
    dupattaDetails: 'Not included.',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43"',
      length: '37" Everyday Kurti',
      sleeve: '20" Quarter Sleeves',
      trouser: 'N/A',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?auto=format&fit=crop&w=800&q=80',
        alt: 'Meena Bazaar Ajrak Inspired Kurti',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80',
        alt: 'Ajrak print pattern view',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-118-IND-S', color: 'Indigo & Rust', colorCode: '#1C39BB', size: 'S', stock: 5 },
      { sku: 'LS-118-IND-M', color: 'Indigo & Rust', colorCode: '#1C39BB', size: 'M', stock: 8 },
      { sku: 'LS-118-IND-L', color: 'Indigo & Rust', colorCode: '#1C39BB', size: 'L', stock: 3 },
    ],
    status: 'active',
    featured: false,
    newArrival: true,
    bestSeller: false,
    sale: false,
  },
  {
    id: 'prod-119',
    name: 'Hoorain Luxury Chiffon Embroidered Maxi Gown',
    slug: 'hoorain-luxury-chiffon-embroidered-maxi-gown',
    sku: 'LS-119',
    description: 'Statement floor-length stitched formal gown. 16 flared kalis with intricate silver tilla work, badla embroidery, and heavy scalloped dupatta. Ideal for valima and reception events.',
    category: 'festive-chiffon',
    tags: ['maxi', 'gown', 'festive', 'chiffon', 'formal', 'wedding'],
    basePrice: 9850,
    compareAtPrice: 11500,
    fabric: 'Pure Silk Crinkle Chiffon',
    shirtDetails: 'Stitched 16-kali flared floor length gown with complete crepe lining (Length: 54").',
    trouserDetails: 'Stitched matching raw silk churidar pyjama.',
    dupattaDetails: 'Heavy embroidered 4-sided matha patti chiffon dupatta (2.75m).',
    measurements: {
      chest: 'Small: 37" | Medium: 40" | Large: 43"',
      length: '54" Floor-Sweeping Maxi Gown',
      sleeve: '22" Sheer Embroidered Sleeves',
      trouser: 'Adjustable Churidar Pajama',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1566737236500-c8ac43014a67?auto=format&fit=crop&w=800&q=80',
        alt: 'Hoorain Luxury Maxi Gown in Powder Lilac',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
        alt: 'Maxi kali embroidery and silver tilla details',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-119-LLC-S', color: 'Powder Lilac', colorCode: '#C8A2C8', size: 'S', stock: 2 },
      { sku: 'LS-119-LLC-M', color: 'Powder Lilac', colorCode: '#C8A2C8', size: 'M', stock: 4 },
      { sku: 'LS-119-LLC-L', color: 'Powder Lilac', colorCode: '#C8A2C8', size: 'L', stock: 1 },
    ],
    status: 'active',
    featured: true,
    newArrival: false,
    bestSeller: true,
    sale: true,
  },
  {
    id: 'prod-120',
    name: 'Pari-Wash Cotton Lawn Printed 3-Piece Suit',
    slug: 'pari-wash-cotton-lawn-printed-3-piece-suit',
    sku: 'LS-120',
    description: 'Serene botanical and Mughal miniature prints on crisp cotton lawn. Paired with a feather-touch pure silk dupatta and dyed cotton cambric trousers.',
    category: '3-piece-suits',
    tags: ['cotton lawn', '3 piece', 'botanical', 'printed', 'silk dupatta'],
    basePrice: 3450,
    compareAtPrice: 3850,
    fabric: 'Crisp Cotton Lawn & Pure Silk',
    shirtDetails: 'Digital botanical printed cotton lawn shirt (3.0m).',
    trouserDetails: 'Dyed pure cotton trouser (2.5m).',
    dupattaDetails: 'Printed 100% medium silk dupatta (2.5m).',
    measurements: {
      chest: 'Small: 38" | Medium: 40" | Large: 43"',
      length: '39" Traditional Straight Cut',
      sleeve: '21" Sleeves',
      trouser: '38" Tailored Straight Trousers',
    },
    images: [
      {
        url: 'https://images.unsplash.com/photo-1515886657613-9f3515b0c78f?auto=format&fit=crop&w=800&q=80',
        alt: 'Pari-Wash Botanical Lawn 3-Piece in Sky Blue',
        isPrimary: true,
      },
      {
        url: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?auto=format&fit=crop&w=800&q=80',
        alt: 'Silk dupatta print and fabric flow',
        isPrimary: false,
      }
    ],
    variants: [
      { sku: 'LS-120-SKY-S', color: 'Sky Blue', colorCode: '#87CEEB', size: 'S', stock: 5 },
      { sku: 'LS-120-SKY-M', color: 'Sky Blue', colorCode: '#87CEEB', size: 'M', stock: 8 },
      { sku: 'LS-120-SKY-L', color: 'Sky Blue', colorCode: '#87CEEB', size: 'L', stock: 4 },
      { sku: 'LS-120-SKY-UN', color: 'Sky Blue', colorCode: '#87CEEB', size: 'Unstitched', stock: 10 },
    ],
    status: 'active',
    featured: false,
    newArrival: true,
    bestSeller: false,
    sale: true,
  }
];
